/**
 * lib/commands.ts — Telegram management command definitions
 * ========================================================
 * 88+ commands across 10 categories for managing Telegram accounts.
 * Each command has input schema and executor function.
 */

export interface CommandParam {
  name: string;
  label: string;
  type: 'text' | 'number' | 'phone' | 'select' | 'textarea' | 'checkbox';
  required: boolean;
  placeholder?: string;
  options?: { label: string; value: string }[];
  defaultValue?: string | number | boolean;
  help?: string;
}

export interface CommandDef {
  id: string;
  name: string;
  label: string;
  description: string;
  category: CommandCategory;
  icon: string;
  params: CommandParam[];
  requiresAccount: boolean;
  danger?: 'low' | 'medium' | 'high';
}

export type CommandCategory =
  | 'account'
  | 'profile'
  | 'messages'
  | 'contacts'
  | 'groups'
  | 'channels'
  | 'privacy'
  | 'security'
  | 'automation'
  | 'utilities'
  | 'scraping'
  | 'mass'
  | 'op3'        // OP3 Adders
  | 'ramex'      // Ramex Adders
  | 'nearby'     // Nearby + countries
  | 'messaging'  // Messaging + sub-options
  | 'reports'    // Reports + types
  | 'engagement' // Engagement
  | 'group_tools' // Group Tools
  | 'account_tools'; // Account Tools

export const COMMAND_CATEGORIES: { id: CommandCategory; label: string; icon: string; color: string }[] = [
  { id: 'account',       label: 'الحساب',          icon: '👤', color: 'blue'   },
  { id: 'account_tools', label: 'أدوات الحساب',     icon: '🔧', color: 'slate'  },
  { id: 'profile',       label: 'الملف الشخصي',    icon: '✨', color: 'purple' },
  { id: 'messages',      label: 'الرسائل',         icon: '💬', color: 'green'  },
  { id: 'messaging',     label: 'المراسلة',         icon: '📨', color: 'teal'   },
  { id: 'contacts',      label: 'جهات الاتصال',     icon: '📇', color: 'orange' },
  { id: 'groups',        label: 'المجموعات',       icon: '👥', color: 'pink'   },
  { id: 'group_tools',   label: 'أدوات المجموعات',  icon: '🛠️', color: 'rose'   },
  { id: 'channels',      label: 'القنوات',         icon: '📢', color: 'cyan'   },
  { id: 'privacy',       label: 'الخصوصية',        icon: '🔒', color: 'red'    },
  { id: 'security',      label: 'الأمان',          icon: '🛡️', color: 'indigo' },
  { id: 'scraping',      label: 'سحب الأعضاء',      icon: '📥', color: 'teal'   },
  { id: 'op3',           label: 'OP3 Adders',       icon: '➕', color: 'emerald' },
  { id: 'ramex',         label: 'Ramex Adders',    icon: '⚡', color: 'amber'   },
  { id: 'nearby',        label: 'Nearby + الدول',   icon: '📍', color: 'lime'   },
  { id: 'engagement',    label: 'Engagement',      icon: '📈', color: 'fuchsia' },
  { id: 'reports',       label: 'التقارير',         icon: '🚩', color: 'rose'   },
  { id: 'automation',    label: 'الأتمتة',         icon: '⚡', color: 'yellow' },
  { id: 'utilities',     label: 'أدوات',           icon: '🛠️', color: 'gray'   },
];

export const COMMANDS: CommandDef[] = [
  // ====== ACCOUNT ======
  {
    id: 'get_me',
    name: 'getMe',
    label: 'معلومات حسابي',
    description: 'عرض المعلومات الأساسية لحسابي على تيليجرام',
    category: 'account',
    icon: '👤',
    params: [],
    requiresAccount: true,
    danger: 'low',
  },
  {
    id: 'get_profile_photos',
    name: 'getProfilePhotos',
    label: 'صور الملف الشخصي',
    description: 'عرض كل صور الملف الشخصي للحساب',
    category: 'account',
    icon: '🖼️',
    params: [],
    requiresAccount: true,
  },
  {
    id: 'change_username',
    name: 'updateUsername',
    label: 'تغيير اسم المستخدم',
    description: 'تغيير الـ @username الخاص بالحساب',
    category: 'account',
    icon: '@',
    params: [
      { name: 'username', label: 'اسم المستخدم الجديد', type: 'text', required: true, placeholder: 'new_username' },
    ],
    requiresAccount: true,
    danger: 'medium',
  },
  {
    id: 'change_name',
    name: 'updateProfile',
    label: 'تغيير الاسم الأول والأخير',
    description: 'تحديث الاسم الأول والأخير والـ bio',
    category: 'account',
    icon: '✏️',
    params: [
      { name: 'firstName', label: 'الاسم الأول', type: 'text', required: true },
      { name: 'lastName', label: 'الاسم الأخير', type: 'text', required: false },
      { name: 'about', label: 'نبذة (Bio)', type: 'textarea', required: false },
    ],
    requiresAccount: true,
    danger: 'medium',
  },
  {
    id: 'change_bio',
    name: 'updateBio',
    label: 'تغيير النبذة',
    description: 'تحديث نص النبذة في الملف الشخصي',
    category: 'account',
    icon: '📝',
    params: [
      { name: 'bio', label: 'النبذة الجديدة', type: 'textarea', required: true, maxLength: 70 },
    ],
    requiresAccount: true,
  },
  {
    id: 'set_profile_photo',
    name: 'setProfilePhoto',
    label: 'تعيين صورة الملف',
    description: 'رفع صورة جديدة للملف الشخصي',
    category: 'account',
    icon: '📷',
    params: [
      { name: 'photoUrl', label: 'رابط الصورة', type: 'text', required: true, placeholder: 'https://...' },
    ],
    requiresAccount: true,
  },
  {
    id: 'delete_profile_photo',
    name: 'deleteProfilePhoto',
    label: 'حذف صورة الملف',
    description: 'حذف صورة الملف الشخصي الحالية',
    category: 'account',
    icon: '🗑️',
    params: [
      { name: 'photoId', label: 'ID الصورة', type: 'text', required: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'account_logout',
    name: 'logOut',
    label: 'تسجيل خروج من تيليجرام',
    description: 'تسجيل خروج نهائي من هذا الحساب على تيليجرام',
    category: 'account',
    icon: '🚪',
    params: [],
    requiresAccount: true,
    danger: 'high',
  },

  // ====== PROFILE ======
  {
    id: 'get_full_info',
    name: 'getFullInfo',
    label: 'المعلومات الكاملة',
    description: 'عرض كل المعلومات المتاحة عن الحساب',
    category: 'profile',
    icon: '📋',
    params: [],
    requiresAccount: true,
  },
  {
    id: 'get_dialogs',
    name: 'getDialogs',
    label: 'كل المحادثات',
    description: 'عرض قائمة بكل المحادثات (دردشات، مجموعات، قنوات)',
    category: 'profile',
    icon: '📂',
    params: [
      { name: 'limit', label: 'الحد الأقصى', type: 'number', required: false, defaultValue: 100 },
    ],
    requiresAccount: true,
  },
  {
    id: 'get_blocked_users',
    name: 'getBlockedUsers',
    label: 'المستخدمون المحظورون',
    description: 'عرض قائمة المستخدمين الذين حظرتهم',
    category: 'profile',
    icon: '🚫',
    params: [],
    requiresAccount: true,
  },

  // ====== MESSAGES ======
  {
    id: 'send_message',
    name: 'sendMessage',
    label: 'إرسال رسالة',
    description: 'إرسال رسالة نصية إلى مستخدم أو مجموعة',
    category: 'messages',
    icon: '✉️',
    params: [
      { name: 'peer', label: 'المستلم (username أو ID)', type: 'text', required: true, placeholder: '@username أو 123456789' },
      { name: 'message', label: 'نص الرسالة', type: 'textarea', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'send_bulk_message',
    name: 'sendBulkMessages',
    label: 'إرسال رسائل جماعية',
    description: 'إرسال رسالة إلى عدة مستخدمين دفعة واحدة',
    category: 'messages',
    icon: '📨',
    params: [
      { name: 'peers', label: 'قائمة المستلمين (مفصولة بفواصل)', type: 'textarea', required: true, placeholder: '@user1, @user2, 123456789' },
      { name: 'message', label: 'نص الرسالة', type: 'textarea', required: true },
      { name: 'delay', label: 'تأخير بين كل رسالة (ثانية)', type: 'number', required: false, defaultValue: 2 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'forward_messages',
    name: 'forwardMessages',
    label: 'إعادة توجيه رسائل',
    description: 'إعادة توجيه رسائل من محادثة إلى أخرى',
    category: 'messages',
    icon: '↪️',
    params: [
      { name: 'fromPeer', label: 'المحادثة المصدر', type: 'text', required: true },
      { name: 'toPeer', label: 'المحادثة الهدف', type: 'text', required: true },
      { name: 'messageIds', label: 'معرفات الرسائل (مفصولة بفواصل)', type: 'text', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'delete_messages',
    name: 'deleteMessages',
    label: 'حذف رسائل',
    description: 'حذف رسائل من محادثة (للجميع إذا كنت أنت المرسل)',
    category: 'messages',
    icon: '🗑️',
    params: [
      { name: 'peer', label: 'المحادثة', type: 'text', required: true },
      { name: 'messageIds', label: 'معرفات الرسائل', type: 'text', required: true },
      { name: 'revoke', label: 'حذف للجميع', type: 'checkbox', required: false, defaultValue: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'mark_as_read',
    name: 'markAsRead',
    label: 'تعليم كمقروء',
    description: 'تعليم كل رسائل محادثة كمقروءة',
    category: 'messages',
    icon: '✓',
    params: [
      { name: 'peer', label: 'المحادثة', type: 'text', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'get_history',
    name: 'getHistory',
    label: 'سجل الرسائل',
    description: 'عرض آخر الرسائل من محادثة',
    category: 'messages',
    icon: '📜',
    params: [
      { name: 'peer', label: 'المحادثة', type: 'text', required: true },
      { name: 'limit', label: 'عدد الرسائل', type: 'number', required: false, defaultValue: 50 },
    ],
    requiresAccount: true,
  },
  {
    id: 'send_file',
    name: 'sendFile',
    label: 'إرسال ملف',
    description: 'إرسال ملف (صورة، فيديو، مستند) إلى محادثة',
    category: 'messages',
    icon: '📎',
    params: [
      { name: 'peer', label: 'المستلم', type: 'text', required: true },
      { name: 'fileUrl', label: 'رابط الملف', type: 'text', required: true },
      { name: 'caption', label: 'التعليق', type: 'text', required: false },
    ],
    requiresAccount: true,
  },

  // ====== CONTACTS ======
  {
    id: 'get_contacts',
    name: 'getContacts',
    label: 'جهات الاتصال',
    description: 'عرض قائمة جهات الاتصال',
    category: 'contacts',
    icon: '📇',
    params: [],
    requiresAccount: true,
  },
  {
    id: 'add_contact',
    name: 'addContact',
    label: 'إضافة جهة اتصال',
    description: 'إضافة رقم جديد لجهات الاتصال',
    category: 'contacts',
    icon: '➕',
    params: [
      { name: 'phone', label: 'رقم الهاتف', type: 'phone', required: true, placeholder: '+1234567890' },
      { name: 'firstName', label: 'الاسم الأول', type: 'text', required: true },
      { name: 'lastName', label: 'الاسم الأخير', type: 'text', required: false },
    ],
    requiresAccount: true,
  },
  {
    id: 'delete_contact',
    name: 'deleteContact',
    label: 'حذف جهة اتصال',
    description: 'حذف جهة اتصال من القائمة',
    category: 'contacts',
    icon: '❌',
    params: [
      { name: 'userId', label: 'معرف المستخدم', type: 'text', required: true },
    ],
    requiresAccount: true,
    danger: 'medium',
  },
  {
    id: 'block_user',
    name: 'blockUser',
    label: 'حظر مستخدم',
    description: 'حظر مستخدم من التواصل معك',
    category: 'contacts',
    icon: '🚫',
    params: [
      { name: 'userId', label: 'معرف المستخدم', type: 'text', required: true },
    ],
    requiresAccount: true,
    danger: 'medium',
  },
  {
    id: 'unblock_user',
    name: 'unblockUser',
    label: 'إلغاء حظر',
    description: 'إلغاء حظر مستخدم',
    category: 'contacts',
    icon: '✓',
    params: [
      { name: 'userId', label: 'معرف المستخدم', type: 'text', required: true },
    ],
    requiresAccount: true,
  },

  // ====== GROUPS ======
  {
    id: 'create_group',
    name: 'createGroup',
    label: 'إنشاء مجموعة',
    description: 'إنشاء مجموعة جديدة',
    category: 'groups',
    icon: '➕',
    params: [
      { name: 'title', label: 'اسم المجموعة', type: 'text', required: true },
      { name: 'description', label: 'الوصف', type: 'textarea', required: false },
    ],
    requiresAccount: true,
  },
  {
    id: 'join_group',
    name: 'joinGroup',
    label: 'الانضمام لمجموعة',
    description: 'الانضمام إلى مجموعة عبر رابط الدعوة',
    category: 'groups',
    icon: '➡️',
    params: [
      { name: 'inviteLink', label: 'رابط الدعوة', type: 'text', required: true, placeholder: 'https://t.me/+...' },
    ],
    requiresAccount: true,
  },
  {
    id: 'leave_group',
    name: 'leaveGroup',
    label: 'مغادرة مجموعة',
    description: 'مغادرة مجموعة محددة',
    category: 'groups',
    icon: '🚪',
    params: [
      { name: 'groupId', label: 'معرف المجموعة', type: 'text', required: true },
    ],
    requiresAccount: true,
    danger: 'medium',
  },
  {
    id: 'get_participants',
    name: 'getParticipants',
    label: 'أعضاء المجموعة',
    description: 'عرض قائمة أعضاء مجموعة',
    category: 'groups',
    icon: '👥',
    params: [
      { name: 'groupId', label: 'معرف المجموعة', type: 'text', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'kick_member',
    name: 'kickMember',
    label: 'طرد عضو',
    description: 'طرد عضو من مجموعة',
    category: 'groups',
    icon: '👢',
    params: [
      { name: 'groupId', label: 'معرف المجموعة', type: 'text', required: true },
      { name: 'userId', label: 'معرف العضو', type: 'text', required: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'promote_admin',
    name: 'promoteAdmin',
    label: 'ترقية لمشرف',
    description: 'ترقية عضو إلى مشرف في المجموعة',
    category: 'groups',
    icon: '⬆️',
    params: [
      { name: 'groupId', label: 'معرف المجموعة', type: 'text', required: true },
      { name: 'userId', label: 'معرف العضو', type: 'text', required: true },
    ],
    requiresAccount: true,
    danger: 'medium',
  },
  {
    id: 'set_group_title',
    name: 'setGroupTitle',
    label: 'تغيير اسم المجموعة',
    description: 'تغيير اسم مجموعة أنت مشرف فيها',
    category: 'groups',
    icon: '✏️',
    params: [
      { name: 'groupId', label: 'معرف المجموعة', type: 'text', required: true },
      { name: 'title', label: 'الاسم الجديد', type: 'text', required: true },
    ],
    requiresAccount: true,
  },

  // ====== CHANNELS ======
  {
    id: 'create_channel',
    name: 'createChannel',
    label: 'إنشاء قناة',
    description: 'إنشاء قناة بث جديدة',
    category: 'channels',
    icon: '➕',
    params: [
      { name: 'title', label: 'اسم القناة', type: 'text', required: true },
      { name: 'about', label: 'الوصف', type: 'textarea', required: false },
      { name: 'megagroup', label: 'مجموعة كبيرة (بدل قناة)', type: 'checkbox', required: false, defaultValue: false },
    ],
    requiresAccount: true,
  },
  {
    id: 'join_channel',
    name: 'joinChannel',
    label: 'الانضمام لقناة',
    description: 'الاشتراك في قناة',
    category: 'channels',
    icon: '➡️',
    params: [
      { name: 'channelUsername', label: 'معرف القناة', type: 'text', required: true, placeholder: '@channelname' },
    ],
    requiresAccount: true,
  },
  {
    id: 'leave_channel',
    name: 'leaveChannel',
    label: 'مغادرة قناة',
    description: 'إلغاء الاشتراك في قناة',
    category: 'channels',
    icon: '🚪',
    params: [
      { name: 'channelId', label: 'معرف القناة', type: 'text', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'get_channel_members',
    name: 'getChannelMembers',
    label: 'مشتركو القناة',
    description: 'عرض عدد مشتركي قناة',
    category: 'channels',
    icon: '👥',
    params: [
      { name: 'channelId', label: 'معرف القناة', type: 'text', required: true },
    ],
    requiresAccount: true,
  },

  // ====== PRIVACY ======
  {
    id: 'set_phone_privacy',
    name: 'setPhonePrivacy',
    label: 'خصوصية رقم الهاتف',
    description: 'تحديد من يستطيع رؤية رقم هاتفك',
    category: 'privacy',
    icon: '📱',
    params: [
      { name: 'visibility', label: 'الرؤية', type: 'select', required: true, options: [
        { label: 'الجميع', value: 'everybody' },
        { label: 'جهات الاتصال', value: 'contacts' },
        { label: 'لا أحد', value: 'nobody' },
      ]},
    ],
    requiresAccount: true,
  },
  {
    id: 'set_last_seen_privacy',
    name: 'setLastSeenPrivacy',
    label: 'خصوصية آخر ظهور',
    description: 'تحديد من يرى آخر ظهور لك',
    category: 'privacy',
    icon: '⏰',
    params: [
      { name: 'visibility', label: 'الرؤية', type: 'select', required: true, options: [
        { label: 'الجميع', value: 'everybody' },
        { label: 'جهات الاتصال', value: 'contacts' },
        { label: 'لا أحد', value: 'nobody' },
      ]},
    ],
    requiresAccount: true,
  },
  {
    id: 'set_profile_photo_privacy',
    name: 'setProfilePhotoPrivacy',
    label: 'خصوصية صورة الملف',
    description: 'تحديد من يرى صورة ملفك الشخصي',
    category: 'privacy',
    icon: '🖼️',
    params: [
      { name: 'visibility', label: 'الرؤية', type: 'select', required: true, options: [
        { label: 'الجميع', value: 'everybody' },
        { label: 'جهات الاتصال', value: 'contacts' },
        { label: 'لا أحد', value: 'nobody' },
      ]},
    ],
    requiresAccount: true,
  },
  {
    id: 'set_add_by_phone_privacy',
    name: 'setAddByPhonePrivacy',
    label: 'إضاقة عبر الهاتف',
    description: 'من يمكنه إضافتك للمجموعات عبر رقمك',
    category: 'privacy',
    icon: '📵',
    params: [
      { name: 'visibility', label: 'الرؤية', type: 'select', required: true, options: [
        { label: 'الجميع', value: 'everybody' },
        { label: 'جهات الاتصال', value: 'contacts' },
        { label: 'لا أحد', value: 'nobody' },
      ]},
    ],
    requiresAccount: true,
  },

  // ====== SECURITY ======
  {
    id: 'enable_2fa',
    name: 'enable2FA',
    label: 'تفعيل التحقق الثنائي',
    description: 'تفعيل كلمة مرور ثنائية على الحساب',
    category: 'security',
    icon: '🔐',
    params: [
      { name: 'password', label: 'كلمة المرور الجديدة', type: 'text', required: true },
      { name: 'hint', label: 'تلميح', type: 'text', required: false },
      { name: 'email', label: 'بريد الاستعادة', type: 'text', required: false },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'change_2fa',
    name: 'change2FA',
    label: 'تغيير كلمة 2FA',
    description: 'تغيير كلمة مرور التحقق الثنائي',
    category: 'security',
    icon: '🔑',
    params: [
      { name: 'currentPassword', label: 'كلمة المرور الحالية', type: 'text', required: true },
      { name: 'newPassword', label: 'كلمة المرور الجديدة', type: 'text', required: true },
      { name: 'hint', label: 'تلميح جديد', type: 'text', required: false },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'disable_2fa',
    name: 'disable2FA',
    label: 'تعطيل التحقق الثنائي',
    description: 'إزالة كلمة مرور التحقق الثنائي',
    category: 'security',
    icon: '🔓',
    params: [
      { name: 'currentPassword', label: 'كلمة المرور الحالية', type: 'text', required: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'get_active_sessions',
    name: 'getActiveSessions',
    label: 'الجلسات النشطة',
    description: 'عرض كل الأجهزة المسجلة دخولها على حسابك',
    category: 'security',
    icon: '💻',
    params: [],
    requiresAccount: true,
  },
  {
    id: 'terminate_session',
    name: 'terminateSession',
    label: 'إنهاء جلسة',
    description: 'تسجيل خروج جهاز معين من حسابك',
    category: 'security',
    icon: '🛑',
    params: [
      { name: 'sessionHash', label: 'معرف الجلسة', type: 'text', required: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'terminate_all_other_sessions',
    name: 'terminateAllOtherSessions',
    label: 'إنهاء كل الجلسات الأخرى',
    description: 'تسجيل خروج من كل الأجهزة ما عدا الحالي',
    category: 'security',
    icon: '🛡️',
    params: [],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'get_login_codes',
    name: 'getLoginCodes',
    label: 'رموز تسجيل الدخول',
    description: 'عرض رموز تسجيل الدخول الأخيرة',
    category: 'security',
    icon: '🔢',
    params: [],
    requiresAccount: true,
  },
  {
    id: 'get_password_info',
    name: 'getPasswordInfo',
    label: 'حالة التحقق الثنائي',
    description: 'عرض حالة إعدادات التحقق الثنائي',
    category: 'security',
    icon: 'ℹ️',
    params: [],
    requiresAccount: true,
  },

  // ====== AUTOMATION ======
  {
    id: 'auto_read_all',
    name: 'autoReadAll',
    label: 'تعليم الكل كمقروء',
    description: 'تعليم كل الرسائل في كل المحادثات كمقروءة',
    category: 'automation',
    icon: '✓✓',
    params: [],
    requiresAccount: true,
  },
  {
    id: 'auto_accept_join_requests',
    name: 'autoAcceptJoinRequests',
    label: 'قبول طلبات الانضمام',
    description: 'قبول كل طلبات الانضمام في مجموعة',
    category: 'automation',
    icon: '✓',
    params: [
      { name: 'groupId', label: 'معرف المجموعة', type: 'text', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'archive_all_dialogs',
    name: 'archiveAllDialogs',
    label: 'أرشفة كل المحادثات',
    description: 'أرشفة كل المحادثات دفعة واحدة',
    category: 'automation',
    icon: '📦',
    params: [],
    requiresAccount: true,
    danger: 'medium',
  },
  {
    id: 'delete_all_dialogs',
    name: 'deleteAllDialogs',
    label: 'حذف كل المحادثات',
    description: 'حذف كل المحادثات (خطير! لا يمكن التراجع)',
    category: 'automation',
    icon: '⚠️',
    params: [
      { name: 'confirm', label: 'أكِّد بكتابة "DELETE"', type: 'text', required: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },

  // ====== UTILITIES ======
  {
    id: 'resolve_username',
    name: 'resolveUsername',
    label: 'تحليل معرف',
    description: 'تحويل @username إلى معلومات المستخدم/القناة',
    category: 'utilities',
    icon: '🔍',
    params: [
      { name: 'username', label: 'اسم المستخدم', type: 'text', required: true, placeholder: '@username' },
    ],
    requiresAccount: true,
  },
  {
    id: 'get_entity_info',
    name: 'getEntityInfo',
    label: 'معلومات جهة',
    description: 'معلومات كاملة عن مستخدم/مجموعة/قناة',
    category: 'utilities',
    icon: '📋',
    params: [
      { name: 'peer', label: 'المعرف', type: 'text', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'get_chat_info',
    name: 'getChatInfo',
    label: 'معلومات محادثة',
    description: 'معلومات تفصيلية عن محادثة',
    category: 'utilities',
    icon: 'ℹ️',
    params: [
      { name: 'peer', label: 'المحادثة', type: 'text', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'search_messages',
    name: 'searchMessages',
    label: 'بحث في الرسائل',
    description: 'البحث عن رسائل تحتوي على نص معين',
    category: 'utilities',
    icon: '🔎',
    params: [
      { name: 'query', label: 'نص البحث', type: 'text', required: true },
      { name: 'peer', label: 'في محادثة (اختياري)', type: 'text', required: false },
      { name: 'limit', label: 'الحد الأقصى', type: 'number', required: false, defaultValue: 20 },
    ],
    requiresAccount: true,
  },
  {
    id: 'check_username_available',
    name: 'checkUsernameAvailable',
    label: 'توفّر اسم مستخدم',
    description: 'التحقق إذا كان @username متاحاً للتسجيل',
    category: 'utilities',
    icon: '?',
    params: [
      { name: 'username', label: 'اسم المستخدم', type: 'text', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'get_dialogs_count',
    name: 'getDialogsCount',
    label: 'عدد المحادثات',
    description: 'إجمالي عدد المحادثات',
    category: 'utilities',
    icon: '#',
    params: [],
    requiresAccount: true,
  },
  {
    id: 'ping_account',
    name: 'pingAccount',
    label: 'فحص نشاط الحساب',
    description: 'التحقق من أن الحساب نشط ويستجيب',
    category: 'utilities',
    icon: '🏓',
    params: [],
    requiresAccount: true,
  },

  // ====== SCRAPING (سحب الأعضاء) ======
  {
    id: 'scrape_group_members',
    name: 'scrapeGroupMembers',
    label: 'سحب أعضاء مجموعة',
    description: 'استخراج قائمة كاملة بأعضاء مجموعة/قناة (معرف، اسم، username)',
    category: 'scraping',
    icon: '📥',
    params: [
      { name: 'groupPeer', label: 'المجموعة المصدر', type: 'text', required: true, placeholder: '@groupname أو -100xxx' },
      { name: 'limit', label: 'الحد الأقصى للأعضاء', type: 'number', required: false, defaultValue: 1000, help: '0 = كل الأعضاء' },
      { name: 'filterBots', label: 'استبعاد البوتات', type: 'checkbox', required: false, defaultValue: true },
      { name: 'filterDeleted', label: 'استبعاد الحسابات المحذوفة', type: 'checkbox', required: false, defaultValue: true },
      { name: 'filterPremium', label: 'فقط حسابات Premium', type: 'checkbox', required: false, defaultValue: false },
    ],
    requiresAccount: true,
    danger: 'medium',
  },
  {
    id: 'scrape_online_members',
    name: 'scrapeOnlineMembers',
    label: 'سحب الأعضاء النشطين',
    description: 'استخراج الأعضاء المتصلين حالياً في مجموعة',
    category: 'scraping',
    icon: '🟢',
    params: [
      { name: 'groupPeer', label: 'المجموعة', type: 'text', required: true, placeholder: '@groupname' },
      { name: 'limit', label: 'الحد الأقصى', type: 'number', required: false, defaultValue: 200 },
    ],
    requiresAccount: true,
  },
  {
    id: 'scrape_admins',
    name: 'scrapeAdmins',
    label: 'سحب المشرفين',
    description: 'استخراج قائمة المشرفين في مجموعة/قناة',
    category: 'scraping',
    icon: '👑',
    params: [
      { name: 'groupPeer', label: 'المجموعة/القناة', type: 'text', required: true, placeholder: '@groupname' },
    ],
    requiresAccount: true,
  },
  {
    id: 'scrape_bots',
    name: 'scrapeBots',
    label: 'سحب البوتات',
    description: 'استخراج قائمة البوتات الموجودة في مجموعة',
    category: 'scraping',
    icon: '🤖',
    params: [
      { name: 'groupPeer', label: 'المجموعة', type: 'text', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'scrape_recent_users',
    name: 'scrapeRecentUsers',
    label: 'آخر المستخدمين النشطين',
    description: 'عرض آخر 100 مستخدم نشط في المجموعة',
    category: 'scraping',
    icon: '⏰',
    params: [
      { name: 'groupPeer', label: 'المجموعة', type: 'text', required: true },
    ],
    requiresAccount: true,
  },

  // ====== MASS OPERATIONS (العمليات الجماعية) ======
  {
    id: 'mass_add_members',
    name: 'massAddMembers',
    label: 'إضافة أعضاء جماعية',
    description: 'إضافة قائمة من المستخدمين إلى مجموعة/قناة (من قروب مصدر إلى قروب هدف)',
    category: 'mass',
    icon: '➕',
    params: [
      { name: 'targetPeer', label: 'المجموعة الهدف', type: 'text', required: true, placeholder: '@targetgroup' },
      { name: 'userList', label: 'قائمة المستخدمين (usernames أو IDs، واحد لكل سطر)', type: 'textarea', required: true, placeholder: '@user1\n@user2\n123456789\n...' },
      { name: 'delay', label: 'التأخير بين الإضافات (ثانية)', type: 'number', required: false, defaultValue: 5, help: 'موصى به: 5-15 ثانية لتجنب FloodWait' },
      { name: 'stopOnFlood', label: 'توقف عند FloodWait', type: 'checkbox', required: false, defaultValue: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'transfer_members',
    name: 'transferMembers',
    label: 'نقل أعضاء من قروب لآخر',
    description: 'سحب الأعضاء من مجموعة مصدر وإضافتهم لمجموعة هدف (العملية الكاملة)',
    category: 'mass',
    icon: '🔄',
    params: [
      { name: 'sourcePeer', label: 'المجموعة المصدر', type: 'text', required: true, placeholder: '@sourcegroup' },
      { name: 'targetPeer', label: 'المجموعة الهدف', type: 'text', required: true, placeholder: '@targetgroup' },
      { name: 'limit', label: 'الحد الأقصى للنقل', type: 'number', required: false, defaultValue: 50, help: 'موصى به: 30-50 يومياً لتفادي الحظر' },
      { name: 'delay', label: 'التأخير بين الإضافات (ثانية)', type: 'number', required: false, defaultValue: 10 },
      { name: 'filterBots', label: 'تخطي البوتات', type: 'checkbox', required: false, defaultValue: true },
      { name: 'filterDeleted', label: 'تخطي الحسابات المحذوفة', type: 'checkbox', required: false, defaultValue: true },
      { name: 'stopOnFlood', label: 'توقف عند FloodWait', type: 'checkbox', required: false, defaultValue: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'mass_dm',
    name: 'massDM',
    label: 'إرسال رسائل جماعية',
    description: 'إرسال رسالة خاصة لقائمة من المستخدمين',
    category: 'mass',
    icon: '✉️',
    params: [
      { name: 'userList', label: 'قائمة المستلمين (username أو ID، واحد لكل سطر)', type: 'textarea', required: true, placeholder: '@user1\n@user2\n123456789' },
      { name: 'message', label: 'نص الرسالة', type: 'textarea', required: true },
      { name: 'delay', label: 'التأخير (ثانية)', type: 'number', required: false, defaultValue: 5 },
      { name: 'stopOnFlood', label: 'توقف عند FloodWait', type: 'checkbox', required: false, defaultValue: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'mass_dm_group_members',
    name: 'massDMGroupMembers',
    label: 'DM جماعي لأعضاء قروب',
    description: 'سحب أعضاء مجموعة ثم إرسال رسالة خاصة لكل واحد',
    category: 'mass',
    icon: '📢',
    params: [
      { name: 'groupPeer', label: 'المجموعة المصدر', type: 'text', required: true, placeholder: '@groupname' },
      { name: 'message', label: 'نص الرسالة', type: 'textarea', required: true },
      { name: 'limit', label: 'الحد الأقصى للمراسلة', type: 'number', required: false, defaultValue: 30 },
      { name: 'delay', label: 'التأخير (ثانية)', type: 'number', required: false, defaultValue: 15 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'mass_kick',
    name: 'massKick',
    label: 'طرد جماعي',
    description: 'طرد قائمة من المستخدمين من مجموعة',
    category: 'mass',
    icon: '👢',
    params: [
      { name: 'groupPeer', label: 'المجموعة', type: 'text', required: true },
      { name: 'userList', label: 'قائمة المستخدمين (IDs، واحد لكل سطر)', type: 'textarea', required: true },
      { name: 'delay', label: 'التأخير (ثانية)', type: 'number', required: false, defaultValue: 2 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'mass_promote',
    name: 'massPromote',
    label: 'ترقية جماعية لمشرف',
    description: 'ترقية عدة مستخدمين لمشرفين في مجموعة',
    category: 'mass',
    icon: '⬆️',
    params: [
      { name: 'groupPeer', label: 'المجموعة', type: 'text', required: true },
      { name: 'userList', label: 'قائمة المستخدمين (IDs أو usernames)', type: 'textarea', required: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'mass_ban',
    name: 'massBan',
    label: 'حظر جماعي',
    description: 'حظر قائمة من المستخدمين من مجموعة',
    category: 'mass',
    icon: '⛔',
    params: [
      { name: 'groupPeer', label: 'المجموعة', type: 'text', required: true },
      { name: 'userList', label: 'قائمة المستخدمين', type: 'textarea', required: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'mass_mute',
    name: 'massMute',
    label: 'كتم جماعي',
    description: 'كتم عدة مستخدمين في مجموعة',
    category: 'mass',
    icon: '🔇',
    params: [
      { name: 'groupPeer', label: 'المجموعة', type: 'text', required: true },
      { name: 'userList', label: 'قائمة المستخدمين', type: 'textarea', required: true },
      { name: 'duration', label: 'مدة الكتم (دقائق)', type: 'number', required: false, defaultValue: 60 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'mass_unmute',
    name: 'massUnmute',
    label: 'إلغاء الكتم الجماعي',
    description: 'إلغاء كتم عدة مستخدمين في مجموعة',
    category: 'mass',
    icon: '🔊',
    params: [
      { name: 'groupPeer', label: 'المجموعة', type: 'text', required: true },
      { name: 'userList', label: 'قائمة المستخدمين', type: 'textarea', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'mass_pin_messages',
    name: 'massPinMessages',
    label: 'تثبيت رسائل جماعي',
    description: 'تثبيت آخر رسائل في عدة مجموعات',
    category: 'mass',
    icon: '📌',
    params: [
      { name: 'groups', label: 'قائمة المجموعات (واحدة لكل سطر)', type: 'textarea', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'mass_join_groups',
    name: 'massJoinGroups',
    label: 'انضمام جماعي لمجموعات',
    description: 'الانضمام لعدة مجموعات عبر روابط دعوة',
    category: 'mass',
    icon: '➡️',
    params: [
      { name: 'inviteLinks', label: 'روابط الدعوة (واحدة لكل سطر)', type: 'textarea', required: true, placeholder: 'https://t.me/+xxx\nhttps://t.me/+yyy' },
      { name: 'delay', label: 'التأخير (ثانية)', type: 'number', required: false, defaultValue: 10 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'mass_leave_groups',
    name: 'massLeaveGroups',
    label: 'مغادرة جماعية للمجموعات',
    description: 'مغادرة كل المجموعات التي أنت عضو فيها',
    category: 'mass',
    icon: '🚪',
    params: [
      { name: 'confirm', label: 'أكِّد بكتابة "LEAVE"', type: 'text', required: true },
      { name: 'delay', label: 'التأخير (ثانية)', type: 'number', required: false, defaultValue: 3 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'mass_read_messages',
    name: 'massReadMessages',
    label: 'تعليم الكل كمقروء',
    description: 'تعليم كل الرسائل في كل المحادثات كمقروءة',
    category: 'mass',
    icon: '✓✓',
    params: [],
    requiresAccount: true,
  },
  {
    id: 'mass_delete_dialogs',
    name: 'massDeleteDialogs',
    label: 'حذف كل المحادثات',
    description: 'حذف كل المحادثات من حسابك (لا يمكن التراجع!)',
    category: 'mass',
    icon: '🗑️',
    params: [
      { name: 'confirm', label: 'أكِّد بكتابة "DELETE"', type: 'text', required: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'mass_react_messages',
    name: 'massReactMessages',
    label: 'تفاعل جماعي',
    description: 'إضافة تفاعل (react) لآخر رسائل في عدة محادثات',
    category: 'mass',
    icon: '❤️',
    params: [
      { name: 'groupPeer', label: 'المجموعة', type: 'text', required: true },
      { name: 'emoji', label: 'الإيموجي', type: 'text', required: true, defaultValue: '👍' },
      { name: 'limit', label: 'عدد الرسائل', type: 'number', required: false, defaultValue: 20 },
    ],
    requiresAccount: true,
  },
  {
    id: 'export_members_csv',
    name: 'exportMembersCSV',
    label: 'تصدير الأعضاء CSV',
    description: 'تصدير قائمة أعضاء مجموعة بصيغة CSV (للـ Excel)',
    category: 'scraping',
    icon: '📊',
    params: [
      { name: 'groupPeer', label: 'المجموعة', type: 'text', required: true },
      { name: 'limit', label: 'الحد الأقصى', type: 'number', required: false, defaultValue: 1000 },
    ],
    requiresAccount: true,
  },
  {
    id: 'check_phone_in_group',
    name: 'checkPhoneInGroup',
    label: 'فحص وجود رقم في مجموعة',
    description: 'التحقق إذا كان رقم هاتف معين عضواً في مجموعة',
    category: 'scraping',
    icon: '🔍',
    params: [
      { name: 'groupPeer', label: 'المجموعة', type: 'text', required: true },
      { name: 'phone', label: 'رقم الهاتف', type: 'phone', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'scrape_group_info',
    name: 'scrapeGroupInfo',
    label: 'معلومات مجموعة كاملة',
    description: 'استخراج كل المعلومات عن مجموعة (عدد الأعضاء، الوصف، القواعد، المشرفون)',
    category: 'scraping',
    icon: '📋',
    params: [
      { name: 'groupPeer', label: 'المجموعة', type: 'text', required: true },
    ],
    requiresAccount: true,
  },

  // ============================================================================
  // OP3 ADDERS (11) — إضافة أعضاء بطرق متعددة
  // ============================================================================
  {
    id: 'op3_add_from_list',
    name: 'op3AddFromList',
    label: 'OP3: إضافة من قائمة',
    description: 'إضافة أعضاء لقروب هدف من قائمة usernames/IDs جاهزة',
    category: 'op3',
    icon: '➕',
    params: [
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true, placeholder: '@target' },
      { name: 'userList', label: 'القائمة (واحد لكل سطر)', type: 'textarea', required: true },
      { name: 'delay', label: 'التأخير (ثانية)', type: 'number', required: false, defaultValue: 5 },
      { name: 'batchSize', label: 'حجم الدفعة الواحدة', type: 'number', required: false, defaultValue: 1, help: 'تيليجرام يسمح بحد أقصى 200/دفعة لكن ننصح بـ 1' },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'op3_add_from_file',
    name: 'op3AddFromFile',
    label: 'OP3: إضافة من ملف',
    description: 'إضافة أعضاء من ملف CSV/TXT مرفوع (معرفات أو usernames)',
    category: 'op3',
    icon: '📄',
    params: [
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'fileContent', label: 'محتوى الملف (الصق هنا)', type: 'textarea', required: true },
      { name: 'delay', label: 'التأخير (ثانية)', type: 'number', required: false, defaultValue: 5 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'op3_add_from_group',
    name: 'op3AddFromGroup',
    label: 'OP3: نقل من قروب مصدر',
    description: 'سحب أعضاء من قروب مصدر وإضافتهم لقروب الهدف',
    category: 'op3',
    icon: '🔄',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'limit', label: 'العدد', type: 'number', required: false, defaultValue: 30 },
      { name: 'delay', label: 'التأخير (ثانية)', type: 'number', required: false, defaultValue: 10 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'op3_add_active_members',
    name: 'op3AddActiveMembers',
    label: 'OP3: إضافة الأعضاء النشطين',
    description: 'سحب آخر الأعضاء النشطين من قروب مصدر وإضافتهم',
    category: 'op3',
    icon: '🟢',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'limit', label: 'العدد', type: 'number', required: false, defaultValue: 20 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'op3_add_admins',
    name: 'op3AddAdmins',
    label: 'OP3: إضافة المشرفين',
    description: 'سحب المشرفين من قروب مصدر وإضافتهم',
    category: 'op3',
    icon: '👑',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
    ],
    requiresAccount: true,
    danger: 'medium',
  },
  {
    id: 'op3_add_premium_users',
    name: 'op3AddPremiumUsers',
    label: 'OP3: إضافة مستخدمي Premium',
    description: 'سحب مستخدمي Premium من قروب مصدر وإضافتهم',
    category: 'op3',
    icon: '⭐',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'limit', label: 'العدد', type: 'number', required: false, defaultValue: 10 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'op3_add_online_users',
    name: 'op3AddOnlineUsers',
    label: 'OP3: إضافة المتصلين الآن',
    description: 'سحب الأعضاء المتصلين حالياً من قروب وإضافتهم لقروب آخر',
    category: 'op3',
    icon: '🔵',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'limit', label: 'العدد', type: 'number', required: false, defaultValue: 15 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'op3_add_by_country',
    name: 'op3AddByCountry',
    label: 'OP3: إضافة حسب الدولة',
    description: 'تصفية أعضاء قروب مصدر حسب الدولة وإضافتهم لقروب هدف',
    category: 'op3',
    icon: '🌍',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'country', label: 'رمز الدولة (مثل: SA, AE, EG)', type: 'text', required: true },
      { name: 'limit', label: 'العدد', type: 'number', required: false, defaultValue: 20 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'op3_add_by_username_pattern',
    name: 'op3AddByUsernamePattern',
    label: 'OP3: إضافة حسب نمط الاسم',
    description: 'تصفية حسب نمط في username (مثل: _sa, _uae)',
    category: 'op3',
    icon: '🔍',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'pattern', label: 'النمط (مثل: _sa)', type: 'text', required: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'op3_add_recent_joiners',
    name: 'op3AddRecentJoiners',
    label: 'OP3: إضافة المنضمين حديثاً',
    description: 'سحب آخر منضمين لقروب مصدر وإضافتهم',
    category: 'op3',
    icon: '🆕',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'limit', label: 'العدد', type: 'number', required: false, defaultValue: 15 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'op3_multi_target_add',
    name: 'op3MultiTargetAdd',
    label: 'OP3: إضافة لعدة قروبات',
    description: 'إضافة نفس المستخدم لعدة قروبات هدف دفعة واحدة',
    category: 'op3',
    icon: '🎯',
    params: [
      { name: 'userList', label: 'قائمة المستخدمين', type: 'textarea', required: true },
      { name: 'targetPeers', label: 'قائمة القروبات الهدف (واحد لكل سطر)', type: 'textarea', required: true },
      { name: 'delay', label: 'التأخير (ثانية)', type: 'number', required: false, defaultValue: 10 },
    ],
    requiresAccount: true,
    danger: 'high',
  },

  // ============================================================================
  // RAMEX ADDERS (7) — إضافة بطرق متقدمة
  // ============================================================================
  {
    id: 'ramex_clone_group',
    name: 'ramexCloneGroup',
    label: 'Ramex: استنساخ قروب كامل',
    description: 'نسخ كل أعضاء قروب مصدر وإضافتهم لقروب هدف جديد',
    category: 'ramex',
    icon: '⚡',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'limit', label: 'الحد الأقصى', type: 'number', required: false, defaultValue: 100 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'ramex_incremental_add',
    name: 'ramexIncrementalAdd',
    label: 'Ramex: إضافة تدريجية',
    description: 'إضافة X عضو كل Y دقيقة لتفادي FloodWait',
    category: 'ramex',
    icon: '📈',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'batchSize', label: 'عدد الإضافات لكل دفعة', type: 'number', required: false, defaultValue: 5 },
      { name: 'intervalMinutes', label: 'الفاصل بالدقائق', type: 'number', required: false, defaultValue: 30 },
      { name: 'totalBatches', label: 'عدد الدفعات', type: 'number', required: false, defaultValue: 5 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'ramex_filter_add',
    name: 'ramexFilterAdd',
    label: 'Ramex: إضافة مع تصفية متقدمة',
    description: 'تصفية حسب: العمر، آخر ظهور، Premium، البوتات، المحذوفين',
    category: 'ramex',
    icon: '🎛️',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'filterBots', label: 'استبعاد البوتات', type: 'checkbox', required: false, defaultValue: true },
      { name: 'filterDeleted', label: 'استبعاد المحذوفين', type: 'checkbox', required: false, defaultValue: true },
      { name: 'onlyPremium', label: 'فقط Premium', type: 'checkbox', required: false, defaultValue: false },
      { name: 'onlyWithUsername', label: 'فقط لديهم username', type: 'checkbox', required: false, defaultValue: false },
      { name: 'limit', label: 'العدد', type: 'number', required: false, defaultValue: 30 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'ramex_smart_distribute',
    name: 'ramexSmartDistribute',
    label: 'Ramex: توزيع ذكي',
    description: 'توزيع أعضاء قروب مصدر على عدة قروبات هدف بالتساوي',
    category: 'ramex',
    icon: '⚖️',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeers', label: 'القروبات الهدف (واحد لكل سطر)', type: 'textarea', required: true },
      { name: 'membersPerTarget', label: 'عدد لكل قروب', type: 'number', required: false, defaultValue: 10 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'ramex_skip_existing',
    name: 'ramexSkipExisting',
    label: 'Ramex: تخطي الموجودين',
    description: 'إضافة أعضاء فقط غير موجودين أصلاً في القروب الهدف',
    category: 'ramex',
    icon: '⏭️',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'limit', label: 'العدد', type: 'number', required: false, defaultValue: 30 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'ramex_round_robin',
    name: 'ramexRoundRobin',
    label: 'Ramex: Round Robin',
    description: 'إضافة أعضاء بالتناوب بين عدة حسابات لتفادي الحظر',
    category: 'ramex',
    icon: '🔄',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'limit', label: 'العدد الإجمالي', type: 'number', required: false, defaultValue: 30 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'ramex_geo_targeted',
    name: 'ramexGeoTargeted',
    label: 'Ramex: استهداف جغرافي',
    description: 'إضافة أعضاء حسب الموقع الجغرافي (يحتاج Pro)',
    category: 'ramex',
    icon: '🌐',
    params: [
      { name: 'sourcePeer', label: 'القروب المصدر', type: 'text', required: true },
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'countries', label: 'الدول (مفصولة بفواصل)', type: 'text', required: true, placeholder: 'SA,AE,EG' },
    ],
    requiresAccount: true,
    danger: 'high',
  },

  // ============================================================================
  // NEARBY (3 + 20 دولة) — استهداف جغرافي
  // ============================================================================
  {
    id: 'nearby_find_users',
    name: 'nearbyFindUsers',
    label: 'Nearby: العثور على مستخدمين قريبين',
    description: 'البحث عن مستخدمين تيليجرام قريبين جغرافياً (يتطلب موقع)',
    category: 'nearby',
    icon: '📍',
    params: [
      { name: 'latitude', label: 'خط العرض', type: 'text', required: true, placeholder: '24.7136' },
      { name: 'longitude', label: 'خط الطول', type: 'text', required: true, placeholder: '46.6753' },
      { name: 'radius', label: 'النطاق (متر)', type: 'number', required: false, defaultValue: 1000 },
    ],
    requiresAccount: true,
  },
  {
    id: 'nearby_add_users',
    name: 'nearbyAddUsers',
    label: 'Nearby: إضافة قريبين لقروب',
    description: 'سحب المستخدمين القريبين وإضافتهم لقروب',
    category: 'nearby',
    icon: '📍➕',
    params: [
      { name: 'targetPeer', label: 'القروب الهدف', type: 'text', required: true },
      { name: 'latitude', label: 'خط العرض', type: 'text', required: true },
      { name: 'longitude', label: 'خط الطول', type: 'text', required: true },
      { name: 'limit', label: 'العدد', type: 'number', required: false, defaultValue: 10 },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'nearby_country_search',
    name: 'nearbyCountrySearch',
    label: 'Nearby: بحث حسب الدولة',
    description: 'البحث عن مستخدمين في دولة محددة (20 دولة مدعومة)',
    category: 'nearby',
    icon: '🌍',
    params: [
      { name: 'country', label: 'الدولة', type: 'select', required: true, options: [
        { label: '🇸🇦 السعودية', value: 'SA' },
        { label: '🇦🇪 الإمارات', value: 'AE' },
        { label: '🇪🇬 مصر', value: 'EG' },
        { label: '🇰🇼 الكويت', value: 'KW' },
        { label: '🇶🇦 قطر', value: 'QA' },
        { label: '🇧🇭 البحرين', value: 'BH' },
        { label: '🇴🇲 عمان', value: 'OM' },
        { label: '🇯🇴 الأردن', value: 'JO' },
        { label: '🇱🇧 لبنان', value: 'LB' },
        { label: '🇮🇶 العراق', value: 'IQ' },
        { label: '🇸🇾 سوريا', value: 'SY' },
        { label: '🇾🇪 اليمن', value: 'YE' },
        { label: '🇵🇸 فلسطين', value: 'PS' },
        { label: '🇸🇩 السودان', value: 'SD' },
        { label: '🇱🇾 ليبيا', value: 'LY' },
        { label: '🇹🇳 تونس', value: 'TN' },
        { label: '🇩🇿 الجزائر', value: 'DZ' },
        { label: '🇲🇦 المغرب', value: 'MA' },
        { label: '🇲🇷 موريتانيا', value: 'MR' },
        { label: '🇸🇴 الصومال', value: 'SO' },
      ]},
      { name: 'targetPeer', label: 'القروب الهدف (اختياري)', type: 'text', required: false },
    ],
    requiresAccount: true,
  },

  // ============================================================================
  // MESSAGING (4 + 15 خيار فرعي)
  // ============================================================================
  {
    id: 'msg_send_text',
    name: 'msgSendText',
    label: 'إرسال نصي',
    description: 'إرسال رسالة نصية لمستخدم/قروب',
    category: 'messaging',
    icon: '✉️',
    params: [
      { name: 'peer', label: 'المستلم', type: 'text', required: true },
      { name: 'message', label: 'الرسالة', type: 'textarea', required: true },
      { name: 'scheduledFor', label: 'جدولة لاحقاً (اختياري - ISO date)', type: 'text', required: false },
      { name: 'silent', label: 'إرسال صامت (بدون إشعار)', type: 'checkbox', required: false, defaultValue: false },
      { name: 'pin', label: 'تثبيت الرسالة', type: 'checkbox', required: false, defaultValue: false },
      { name: 'replyToMsgId', label: 'الرد على رسالة (ID)', type: 'number', required: false },
    ],
    requiresAccount: true,
  },
  {
    id: 'msg_send_media',
    name: 'msgSendMedia',
    label: 'إرسال وسائط',
    description: 'إرسال صورة/فيديو/ملف/صوت',
    category: 'messaging',
    icon: '📎',
    params: [
      { name: 'peer', label: 'المستلم', type: 'text', required: true },
      { name: 'fileUrl', label: 'رابط الوسائط', type: 'text', required: true },
      { name: 'caption', label: 'التعليق', type: 'text', required: false },
      { name: 'mediaType', label: 'النوع', type: 'select', required: false, options: [
        { label: 'تلقائي', value: 'auto' },
        { label: 'صورة', value: 'photo' },
        { label: 'فيديو', value: 'video' },
        { label: 'ملف', value: 'document' },
        { label: 'صوت', value: 'audio' },
        { label: 'GIF', value: 'gif' },
      ]},
      { name: 'asSpoiler', label: 'كـ spoiler', type: 'checkbox', required: false, defaultValue: false },
      { name: 'noForwards', label: 'منع إعادة التوجيه', type: 'checkbox', required: false, defaultValue: false },
    ],
    requiresAccount: true,
  },
  {
    id: 'msg_forward',
    name: 'msgForward',
    label: 'توجيه رسائل',
    description: 'إعادة توجيه رسالة/رسائل من محادثة لأخرى',
    category: 'messaging',
    icon: '↪️',
    params: [
      { name: 'fromPeer', label: 'المحادثة المصدر', type: 'text', required: true },
      { name: 'toPeer', label: 'المحادثة الهدف', type: 'text', required: true },
      { name: 'msgIds', label: 'معرفات الرسائل (مفصولة بفواصل)', type: 'text', required: true },
      { name: 'silent', label: 'بدون إشعار', type: 'checkbox', required: false, defaultValue: false },
      { name: 'withAuthor', label: 'إظهار المصدر', type: 'checkbox', required: false, defaultValue: false },
      { name: 'topMsgId', label: 'الرد على موضوع', type: 'number', required: false },
    ],
    requiresAccount: true,
  },
  {
    id: 'msg_poll',
    name: 'msgPoll',
    label: 'إرسال استطلاع',
    description: 'إنشاء استطلاع في قروب/قناة',
    category: 'messaging',
    icon: '📊',
    params: [
      { name: 'peer', label: 'المحادثة', type: 'text', required: true },
      { name: 'question', label: 'السؤال', type: 'text', required: true },
      { name: 'options', label: 'الخيارات (واحد لكل سطر)', type: 'textarea', required: true },
      { name: 'multipleAnswers', label: 'السماح بإجابات متعددة', type: 'checkbox', required: false, defaultValue: false },
      { name: 'publicVoters', label: 'إظهار المصوتين', type: 'checkbox', required: false, defaultValue: false },
      { name: 'closed', label: 'إغلاق الاستطلاع فوراً', type: 'checkbox', required: false, defaultValue: false },
    ],
    requiresAccount: true,
  },

  // ============================================================================
  // REPORTS (4 + 10 أنواع)
  // ============================================================================
  {
    id: 'report_user',
    name: 'reportUser',
    label: 'الإبلاغ عن مستخدم',
    description: 'إرسال بلاغ لتيليجرام عن مستخدم',
    category: 'reports',
    icon: '🚩',
    params: [
      { name: 'peer', label: 'المستخدم', type: 'text', required: true },
      { name: 'reason', label: 'السبب', type: 'select', required: true, options: [
        { label: 'سبام', value: 'spam' },
        { label: 'احتيال', value: 'fraud' },
        { label: 'انتحال', value: 'impersonation' },
        { label: 'محتوى غير قانوني', value: 'illegal' },
        { label: 'إباحي', value: 'pornography' },
        { label: 'كراهية', value: 'hate' },
        { label: 'عنف', value: 'violence' },
        { label: 'أطفال', value: 'child_abuse' },
        { label: 'تنمر', value: 'bullying' },
        { label: 'أخرى', value: 'other' },
      ]},
      { name: 'comment', label: 'تفاصيل إضافية', type: 'textarea', required: false },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'report_message',
    name: 'reportMessage',
    label: 'الإبلاغ عن رسالة',
    description: 'إرسال بلاغ عن رسالة محددة',
    category: 'reports',
    icon: '🚩',
    params: [
      { name: 'peer', label: 'المحادثة', type: 'text', required: true },
      { name: 'msgId', label: 'معرف الرسالة', type: 'number', required: true },
      { name: 'reason', label: 'السبب', type: 'select', required: true, options: [
        { label: 'سبام', value: 'spam' },
        { label: 'احتيال', value: 'fraud' },
        { label: 'انتحال', value: 'impersonation' },
        { label: 'محتوى غير قانوني', value: 'illegal' },
        { label: 'إباحي', value: 'pornography' },
        { label: 'كراهية', value: 'hate' },
        { label: 'عنف', value: 'violence' },
        { label: 'أطفال', value: 'child_abuse' },
        { label: 'تنمر', value: 'bullying' },
        { label: 'أخرى', value: 'other' },
      ]},
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'report_channel',
    name: 'reportChannel',
    label: 'الإبلاغ عن قناة',
    description: 'إرسال بلاغ عن قناة كاملة',
    category: 'reports',
    icon: '🚩',
    params: [
      { name: 'peer', label: 'القناة', type: 'text', required: true },
      { name: 'reason', label: 'السبب', type: 'select', required: true, options: [
        { label: 'سبام', value: 'spam' },
        { label: 'احتيال', value: 'fraud' },
        { label: 'انتحال', value: 'impersonation' },
        { label: 'محتوى غير قانوني', value: 'illegal' },
        { label: 'إباحي', value: 'pornography' },
        { label: 'كراهية', value: 'hate' },
        { label: 'عنف', value: 'violence' },
        { label: 'أطفال', value: 'child_abuse' },
        { label: 'تنمر', value: 'bullying' },
        { label: 'أخرى', value: 'other' },
      ]},
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'report_story',
    name: 'reportStory',
    label: 'الإبلاغ عن ستوري',
    description: 'إرسال بلاغ عن قصة (story) على تيليجرام',
    category: 'reports',
    icon: '🚩',
    params: [
      { name: 'peer', label: 'صاحب الستوري', type: 'text', required: true },
      { name: 'storyId', label: 'معرف الستوري', type: 'number', required: true },
      { name: 'reason', label: 'السبب', type: 'select', required: true, options: [
        { label: 'سبام', value: 'spam' },
        { label: 'احتيال', value: 'fraud' },
        { label: 'انتحال', value: 'impersonation' },
        { label: 'محتوى غير قانوني', value: 'illegal' },
        { label: 'إباحي', value: 'pornography' },
        { label: 'كراهية', value: 'hate' },
        { label: 'عنف', value: 'violence' },
        { label: 'أطفال', value: 'child_abuse' },
        { label: 'تنمر', value: 'bullying' },
        { label: 'أخرى', value: 'other' },
      ]},
    ],
    requiresAccount: true,
    danger: 'high',
  },

  // ============================================================================
  // ACCOUNT TOOLS (7)
  // ============================================================================
  {
    id: 'tool_change_session',
    name: 'toolChangeSession',
    label: 'تجديد جلسة الحساب',
    description: 'إنشاء جلسة جديدة لأمان أكبر',
    category: 'account_tools',
    icon: '🔐',
    params: [],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'tool_export_session',
    name: 'toolExportSession',
    label: 'تصدير ملف الجلسة',
    description: 'تصدير StringSession للاستخدام في أداة أخرى',
    category: 'account_tools',
    icon: '📤',
    params: [],
    requiresAccount: true,
  },
  {
    id: 'tool_import_session',
    name: 'toolImportSession',
    label: 'استيراد جلسة',
    description: 'استيراد StringSession من أداة أخرى',
    category: 'account_tools',
    icon: '📥',
    params: [
      { name: 'sessionString', label: 'StringSession', type: 'textarea', required: true },
    ],
    requiresAccount: false,
  },
  {
    id: 'tool_get_session_info',
    name: 'toolGetSessionInfo',
    label: 'معلومات الجلسة',
    description: 'تفاصيل الجلسة الحالية (DC، الموقع، IP)',
    category: 'account_tools',
    icon: 'ℹ️',
    params: [],
    requiresAccount: true,
  },
  {
    id: 'tool_flood_info',
    name: 'toolFloodInfo',
    label: 'معلومات FloodWait',
    description: 'عرض آخر أخطاء FloodWait على الحساب',
    category: 'account_tools',
    icon: '⏱️',
    params: [],
    requiresAccount: true,
  },
  {
    id: 'tool_dc_info',
    name: 'toolDcInfo',
    label: 'معلومات Data Center',
    description: 'عرض الـ DC الذي يتصل به الحساب',
    category: 'account_tools',
    icon: '🏢',
    params: [],
    requiresAccount: true,
  },
  {
    id: 'tool_account_limits',
    name: 'toolAccountLimits',
    label: 'حدود الحساب',
    description: 'عرض حدود تيليجرام على حسابك (إرسال، إنشاء قروبات، إلخ)',
    category: 'account_tools',
    icon: '⚠️',
    params: [],
    requiresAccount: true,
  },

  // ============================================================================
  // GROUP TOOLS (4)
  // ============================================================================
  {
    id: 'group_anti_delete',
    name: 'groupAntiDelete',
    label: 'منع حذف الرسائل',
    description: 'تسجيل الرسائل المحذوفة في القروب وعرضها',
    category: 'group_tools',
    icon: '🛡️',
    params: [
      { name: 'groupPeer', label: 'القروب', type: 'text', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'group_history_cleanup',
    name: 'groupHistoryCleanup',
    label: 'تنظيف سجل القروب',
    description: 'حذف كل رسائل حسابك في قروب محدد',
    category: 'group_tools',
    icon: '🧹',
    params: [
      { name: 'groupPeer', label: 'القروب', type: 'text', required: true },
      { name: 'confirm', label: 'أكِّد بكتابة "CLEAN"', type: 'text', required: true },
    ],
    requiresAccount: true,
    danger: 'high',
  },
  {
    id: 'group_member_tracker',
    name: 'groupMemberTracker',
    label: 'متتبع دخول/خروج الأعضاء',
    description: 'تتبع من انضم/غادر القروب في آخر 24 ساعة',
    category: 'group_tools',
    icon: '👁️',
    params: [
      { name: 'groupPeer', label: 'القروب', type: 'text', required: true },
    ],
    requiresAccount: true,
  },
  {
    id: 'group_link_converter',
    name: 'groupLinkConverter',
    label: 'محوّل روابط القروبات',
    description: 'تحويل روابط t.me/joinchat/ إلى روابط مباشرة @username',
    category: 'group_tools',
    icon: '🔗',
    params: [
      { name: 'inviteLink', label: 'رابط الدعوة', type: 'text', required: true },
    ],
    requiresAccount: true,
  },

  // ============================================================================
  // ENGAGEMENT (3)
  // ============================================================================
  {
    id: 'eng_mass_reactions',
    name: 'engMassReactions',
    label: 'تفاعلات جماعية',
    description: 'إضافة react لآخر رسائل في عدة قروبات',
    category: 'engagement',
    icon: '❤️',
    params: [
      { name: 'groups', label: 'القروبات (واحد لكل سطر)', type: 'textarea', required: true },
      { name: 'emoji', label: 'الإيموجي', type: 'text', required: true, defaultValue: '❤️' },
      { name: 'limit', label: 'عدد الرسائل لكل قروب', type: 'number', required: false, defaultValue: 10 },
    ],
    requiresAccount: true,
  },
  {
    id: 'eng_view_stories',
    name: 'engViewStories',
    label: 'مشاهدة الستوري',
    description: 'مشاهدة كل ستوريات الأصدقاء تلقائياً',
    category: 'engagement',
    icon: '👀',
    params: [
      { name: 'limit', label: 'الحد الأقصى', type: 'number', required: false, defaultValue: 50 },
    ],
    requiresAccount: true,
  },
  {
    id: 'eng_story_reactions',
    name: 'engStoryReactions',
    label: 'تفاعل مع الستوري',
    description: 'إضافة react لستوريات معينة',
    category: 'engagement',
    icon: '💕',
    params: [
      { name: 'peer', label: 'صاحب الستوري', type: 'text', required: true },
      { name: 'emoji', label: 'الإيموجي', type: 'text', required: true, defaultValue: '❤️' },
    ],
    requiresAccount: true,
  },
];

export function getCommandsByCategory(category: CommandCategory): CommandDef[] {
  return COMMANDS.filter((c) => c.category === category);
}

export function getCommandById(id: string): CommandDef | undefined {
  return COMMANDS.find((c) => c.id === id);
}

export function getCommandStats() {
  return {
    total: COMMANDS.length,
    byCategory: COMMAND_CATEGORIES.map((c) => ({
      category: c,
      count: getCommandsByCategory(c.id).length,
    })),
  };
}
